# -*- coding: utf-8 -*-
"""HW 1 - Practicing Commits

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fWVTEPIoryrhZxSFj1G8_1wD3vfweFNj
"""

print("Hello World!")

print("Second Commit")

print("Third Commit")