# -*- coding: utf-8 -*-
"""QMSS 5072 HW 1 - Practicing Commits Lionel Lang 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBk1_RNPckX9R7yMZoS6nxjqjFQlZOWk

# QMSS 5072 Homework 1
# *Lionel Lang*

### Table of Contents
* [1. Program overview](#bullet1)
* [2. Example Visualization](#bullet2)
* [3. Key Takeaways](#bullet3)

<a class="anchor" id="bullet1"></a>
# Program overview
## Background

The **ESPN API GitHub project** (the `espn_api` package) provides tools to access data from ESPN's Fantasy APIs in a more convenient and *programmatic* way.  
Instead of manually checking scores or standings on the ESPN website, users can write Python code to:

- download league, team, and player information
- analyze fantasy performance over time
- build custom dashboards or alerts for their fantasy leagues

Here is the link to the project on GitHub:  
**[ESPN API GitHub repository](https://github.com/cwendt94/espn-api)**

In this notebook, I will:
- briefly describe what the project does
- show an example plot that could be created using data from this kind of API
- summarize a few **important points** about why this project is useful.

The code will be down below with the sample chart:
"""

import matplotlib.pyplot as plt

# Hypothetical weekly fantasy scores for one team
weeks = [1, 2, 3, 4, 5, 6]
scores = [95, 103, 88, 110, 99, 105]

plt.figure(figsize=(6, 4))
plt.plot(weeks, scores, marker='o', color='darkblue')

plt.title("Example Fantasy Team Scores over the Season")
plt.xlabel("Week")
plt.ylabel("Fantasy Points")
plt.grid(True)

plt.tight_layout()
plt.show()

"""<a class="anchor" id="bullet2"></a>

# Example Visualization

The line plot above is an **example** of how data from the ESPN API project could be visualized.  
Here, each point represents one week of a fantasy season, and the y‑axis shows the total *fantasy points* scored by a single team.

- A rising line suggests that the team is improving over time.
- A sudden drop might indicate injuries, bad matchups, or poor lineup decisions.
- By combining the `espn_api` package with plotting libraries like `matplotlib`, users can quickly explore patterns in their fantasy data.

<a class="anchor" id="bullet3"></a>

# Key Takeaways

To **summarize**, this GitHub project is valuable because it:

- automates access to ESPN fantasy data using Python
- makes it easier to create custom analyses and visualizations
- can be extended to support multiple fantasy sports (football, basketball, and more)

Overall, the ESPN API project helps users move from manually checking scores on a website to *programmatically* analyzing their leagues in a reproducible way； I also practiced good version-control habits by making multiple commits
to my Git repository as I updated this notebook.  
This helped me keep a clear record of my progress and made it easy to
revert or compare changes when necessary.
"""